const Router = require('express')
const router = new Router()
const deviceRouter = require('./deviceRouter')
const accountRouter = require('./accountRouter')
const personRouter = require('./personRouter')
const cardRouter = require('./cardRouter')
const cardTypeRouter = require('./cardTypeRouter')
const cardRequestRouter = require('./cardRequestRouter')
const loanRouter = require('./loanRouter')
const loanTypeRouter = require('./loanTypeRouter')
const loanRequestRouter = require('./loanRequestRouter')
const paymentsGroupRouter = require('./paymentsGroupRouter')
const paymentRouter = require('./paymentRouter')
const userPaymentRouter = require('./userPaymentRouter')
const favouritePaymentRouter = require('./favouritePaymentRouter')
const brandRouter = require('./brandRouter')

router.use('/account', accountRouter)
router.use('/person', personRouter)
router.use('/card', cardRouter)
router.use('/card_type', cardTypeRouter)
router.use('/card_request', cardRequestRouter)
router.use('/loan', loanRouter)
router.use('/loan_type', loanTypeRouter)
router.use('/loan_request', loanRequestRouter)
router.use('/payments_group', paymentsGroupRouter)
router.use('/payment', paymentRouter)
router.use('/user_payment', userPaymentRouter)
router.use('/favourite_payment', favouritePaymentRouter)
router.use('/device', deviceRouter)
router.use('/brand', brandRouter)

module.exports = router