export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ACTIVATION_ROUTE = '/activation'
export const BANK_ROUTE = '/'
export const PERSONAL_ACCOUNT_ROUTE = '/personal_account'
export const CARDS_ROUTE = '/cards'
export const WORKER_ROUTE = '/worker'
